### ISSUE TITLE
plugin errors 

### ISSUE THREAD

**Issue by TymekSL** [kit8379/VelocityBungeeList#1]
[22:30:23 INFO] [org.me.velocitybungeelist.velocity.VelocityList]: VelocityList is starting up...
[22:30:23 ERROR]: Couldn't pass ProxyInitializeEvent to velocitylist 1.0
java.lang.NoClassDefFoundError: com/imaginarycode/minecraft/redisbungee/RedisBungeeAPI
        at org.me.velocitybungeelist.velocity.VelocityList.initialize(VelocityList.java:51) ~[?:?]
        at org.me.velocitybungeelist.velocity.VelocityList.onProxyInitialization(VelocityList.java:35) ~[?:?]
        at org.me.velocitybungeelist.velocity.Lmbda$36.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.3.0-SNAPSHOT-404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.3.0-SNAPSHOT-404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: com.imaginarycode.minecraft.redisbungee.RedisBungeeAPI
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity-3.3.0-SNAPSHOT-404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-3.3.0-SNAPSHOT-404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 9 more

**Comment by TymekSL** [comment]
I need redis to work this ? or redis is optional?
